export const results = [
  {
    article_id: "b05625a1e4f7c3b8c20dad7039d09090",
    title: "This big, bold Carnival is worth the ride",
    link: "https://thewest.com.au/lifestyle/motoring/this-big-bold-carnival-is-worth-the-ride-c-15715959",
    keywords: null,
    creator: ["Olga de Moeller"],
    video_url: null,
    description: "It’s beats any seven-seater SUV",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-10-05 06:19:00",
    pubDateTZ: "UTC",
    image_url:
      "https://images.thewest.com.au/publication/C-15715959/596c35ee88cfbde21530bc98725291cc3d42fe6b-16x9-x0y365w7008h3942.jpg",
    source_id: "thewest",
    source_priority: 106740,
    source_name: "The West",
    source_url: "https://thewest.com.au",
    source_icon: "https://i.bytvi.com/domain_icons/thewest.png",
    language: "english",
    country: ["australia"],
    category: ["entertainment"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: false,
  },
  {
    article_id: "6a8b16b329af98fe306965793d656425",
    title:
      "Numbers show Volkswagen's low-cost models may receive a second chance",
    link: "https://eng.obozrevatel.com/section-news/news-numbers-show-volkswagens-low-cost-models-may-receive-a-second-chance-05-10-2024.html",
    keywords: ["news"],
    creator: null,
    video_url: null,
    description: "The market is not ready to let go of SEAT",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-10-05 06:19:00",
    pubDateTZ: "UTC",
    image_url:
      "https://i2.obozrevatel.com/news/2024/10/5/seat-ateca.jpg?size=2010x1050",
    source_id: "obozrevatel",
    source_priority: 49980,
    source_name: "Obozrevatel",
    source_url: "https://www.obozrevatel.com",
    source_icon: "https://i.bytvi.com/domain_icons/obozrevatel.jpg",
    language: "english",
    country: ["ukraine"],
    category: ["top"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: false,
  },
  {
    article_id: "c59f8b1dbd61d03de47462b9d3c65e07",
    title:
      "Photos: See the action from the Airline vs. Captain Shreve football game",
    link: "https://www.shreveportbossieradvocate.com/multimedia/photos/photos-high-school-football-airline-captain-shreve-shreveport/collection_b7d8da5e-82e0-11ef-b990-37c0d1d0b22c.html",
    keywords: null,
    creator: null,
    video_url: null,
    description:
      "Airline defeated Captain Shreve 69-68 on Friday night in Shreveport",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-10-05 06:19:00",
    pubDateTZ: "UTC",
    image_url:
      "http://bloximages.newyork1.vip.townnews.com/theadvocate.com/content/tncms/assets/v3/editorial/b/f5/bf50d1da-45c4-5707-b35f-651ee6f42c42/6700dd0f46426.preview.jpg?resize=300%2C207",
    source_id: "theadvocate",
    source_priority: 4852,
    source_name: "The Advocate",
    source_url: "https://www.theadvocate.com",
    source_icon: "https://i.bytvi.com/domain_icons/theadvocate.png",
    language: "english",
    country: ["united states of america"],
    category: ["politics"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: false,
  },
  {
    article_id: "65ad22b7627da8b2a3322c713a1e65ed",
    title:
      "Elephant flees Telugu movie set, found 12 hours later in Kerala forest",
    link: "https://www.deccanchronicle.com/southern-states/kerala/elephant-flees-telugu-movie-set-found-12-hours-later-in-kerala-forest-1828210",
    keywords: ["southern states,entertainment,kerala,tollywood,trending"],
    creator: ["PTI"],
    video_url: null,
    description: null,
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-10-05 06:18:54",
    pubDateTZ: "UTC",
    image_url:
      "https://www.deccanchronicle.com/h-upload/2024/10/05/1848567-ezgif-7-a8cb1d5679.webp",
    source_id: "deccanchronicle",
    source_priority: 14130,
    source_name: "Deccan Chronicle",
    source_url: "https://www.deccanchronicle.com",
    source_icon: "https://i.bytvi.com/domain_icons/deccanchronicle.png",
    language: "english",
    country: ["india"],
    category: ["technology"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: false,
  },
  {
    article_id: "ba7baae73de09d3c6ee5b534e523e4c9",
    title:
      "Canandaigua National Bank & Trust Co. Has $2.71 Million Stock Holdings in General Electric (NYSE:GE)",
    link: "https://www.defenseworld.net/2024/10/05/canandaigua-national-bank-trust-co-has-2-71-million-stock-holdings-in-general-electric-nysege.html",
    keywords: ["companies", "sec filing articles"],
    creator: ["Defense World Staff"],
    video_url: null,
    description:
      "Canandaigua National Bank & Trust Co. decreased its stake in shares of General Electric (NYSE:GE – Free Report) by 0.7% during the 3rd quarter, according to the company in its most recent 13F filing with the Securities & Exchange Commission. The institutional investor owned 14,356 shares of the conglomerate’s stock after selling 94 shares during [...]",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-10-05 06:18:53",
    pubDateTZ: "UTC",
    image_url:
      "https://www.marketbeat.com/logos/general-electric-company-logo-1200x675.png",
    source_id: "defenseworld",
    source_priority: 92509,
    source_name: "Defenseworld Net",
    source_url: "https://www.defenseworld.net",
    source_icon: "https://i.bytvi.com/domain_icons/defenseworld.png",
    language: "english",
    country: ["united states of america"],
    category: ["business"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: false,
  },
  {
    article_id: "32279d00a138d71cf71d4f8c55236bd9",
    title:
      "Canandaigua National Bank & Trust Co. Purchases 125 Shares of Amgen Inc. (NASDAQ:AMGN)",
    link: "https://www.defenseworld.net/2024/10/05/canandaigua-national-bank-trust-co-purchases-125-shares-of-amgen-inc-nasdaqamgn.html",
    keywords: ["companies", "sec filing articles"],
    creator: ["Defense World Staff"],
    video_url: null,
    description:
      "Canandaigua National Bank & Trust Co. increased its position in Amgen Inc. (NASDAQ:AMGN – Free Report) by 1.0% in the 3rd quarter, according to the company in its most recent disclosure with the Securities and Exchange Commission (SEC). The firm owned 12,907 shares of the medical research company’s stock after purchasing an additional 125 shares [...]",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-10-05 06:18:53",
    pubDateTZ: "UTC",
    image_url:
      "https://www.marketbeat.com/logos/amgen-inc-logo-1200x675.jpg?v=20231228113741",
    source_id: "defenseworld",
    source_priority: 92509,
    source_name: "Defenseworld Net",
    source_url: "https://www.defenseworld.net",
    source_icon: "https://i.bytvi.com/domain_icons/defenseworld.png",
    language: "english",
    country: ["united states of america"],
    category: ["business"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: false,
  },
  {
    article_id: "9b0defe7396c4a1bcf34904e86ce20c7",
    title:
      "Sterneck Capital Management LLC Cuts Stock Holdings in International Business Machines Co. (NYSE:IBM)",
    link: "https://www.defenseworld.net/2024/10/05/sterneck-capital-management-llc-cuts-stock-holdings-in-international-business-machines-co-nyseibm.html",
    keywords: ["companies", "sec filing articles"],
    creator: ["Defense World Staff"],
    video_url: null,
    description:
      "Sterneck Capital Management LLC cut its stake in shares of International Business Machines Co. (NYSE:IBM – Free Report) by 7.9% in the 3rd quarter, according to its most recent filing with the Securities & Exchange Commission. The firm owned 13,905 shares of the technology company’s stock after selling 1,186 shares during the period. International Business [...]",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-10-05 06:18:53",
    pubDateTZ: "UTC",
    image_url:
      "https://www.marketbeat.com/logos/international-business-machines-co-logo-1200x675.png?v=20221020160751",
    source_id: "defenseworld",
    source_priority: 92509,
    source_name: "Defenseworld Net",
    source_url: "https://www.defenseworld.net",
    source_icon: "https://i.bytvi.com/domain_icons/defenseworld.png",
    language: "english",
    country: ["united states of america"],
    category: ["business"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: false,
  },
  {
    article_id: "9b9fe13a0652ca28c5aeb665fe89fcc4",
    title:
      "Canandaigua National Bank & Trust Co. Sells 3,921 Shares of Alphabet Inc. (NASDAQ:GOOG)",
    link: "https://www.defenseworld.net/2024/10/05/canandaigua-national-bank-trust-co-sells-3921-shares-of-alphabet-inc-nasdaqgoog.html",
    keywords: ["companies", "sec filing articles"],
    creator: ["Defense World Staff"],
    video_url: null,
    description:
      "Canandaigua National Bank & Trust Co. cut its stake in Alphabet Inc. (NASDAQ:GOOG – Free Report) by 6.3% during the third quarter, according to the company in its most recent Form 13F filing with the Securities and Exchange Commission. The fund owned 58,355 shares of the information services provider’s stock after selling 3,921 shares during [...]",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-10-05 06:18:53",
    pubDateTZ: "UTC",
    image_url: "https://www.marketbeat.com/logos/google-inc-logo-1200x675.png",
    source_id: "defenseworld",
    source_priority: 92509,
    source_name: "Defenseworld Net",
    source_url: "https://www.defenseworld.net",
    source_icon: "https://i.bytvi.com/domain_icons/defenseworld.png",
    language: "english",
    country: ["united states of america"],
    category: ["business"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: false,
  },
  {
    article_id: "2ec76b79a1e7fb1af5a6db5641ec6ab9",
    title:
      "Sterneck Capital Management LLC Has $4.16 Million Holdings in KraneShares CSI China Internet ETF (NYSE:KWEB)",
    link: "https://www.defenseworld.net/2024/10/05/sterneck-capital-management-llc-has-4-16-million-holdings-in-kraneshares-csi-china-internet-etf-nysekweb.html",
    keywords: ["companies", "sec filing articles"],
    creator: ["Defense World Staff"],
    video_url: null,
    description:
      "Sterneck Capital Management LLC trimmed its stake in KraneShares CSI China Internet ETF (NYSE:KWEB – Free Report) by 0.5% during the third quarter, according to its most recent disclosure with the Securities and Exchange Commission (SEC). The firm owned 122,138 shares of the company’s stock after selling 644 shares during the period. KraneShares CSI China [...]",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-10-05 06:18:53",
    pubDateTZ: "UTC",
    image_url:
      "https://www.marketbeat.com/logos/kraneshares-csi-china-internet-etf-logo-1200x675.png?v=20240923141809",
    source_id: "defenseworld",
    source_priority: 92509,
    source_name: "Defenseworld Net",
    source_url: "https://www.defenseworld.net",
    source_icon: "https://i.bytvi.com/domain_icons/defenseworld.png",
    language: "english",
    country: ["united states of america"],
    category: ["business"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: false,
  },
  {
    article_id: "b62f9e100edcf480622edb135a5a66d6",
    title:
      "The Walt Disney Company (NYSE:DIS) Shares Sold by Sterneck Capital Management LLC",
    link: "https://www.defenseworld.net/2024/10/05/the-walt-disney-company-nysedis-shares-sold-by-sterneck-capital-management-llc.html",
    keywords: ["companies", "sec filing articles"],
    creator: ["Defense World Staff"],
    video_url: null,
    description:
      "Sterneck Capital Management LLC lessened its stake in The Walt Disney Company (NYSE:DIS – Free Report) by 1.1% in the 3rd quarter, according to the company in its most recent Form 13F filing with the SEC. The fund owned 29,145 shares of the entertainment giant’s stock after selling 320 shares during the quarter. Walt Disney [...]",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-10-05 06:18:52",
    pubDateTZ: "UTC",
    image_url:
      "https://www.marketbeat.com/logos/the-walt-disney-company-logo-1200x675.png?v=20201229105326",
    source_id: "defenseworld",
    source_priority: 92509,
    source_name: "Defenseworld Net",
    source_url: "https://www.defenseworld.net",
    source_icon: "https://i.bytvi.com/domain_icons/defenseworld.png",
    language: "english",
    country: ["united states of america"],
    category: ["business"],
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
    duplicate: false,
  },
];
